version: "3.1"

services:
  db:
    image: postgres
    container_name: db_control_fc
    restart: always
    ports:
      - 5433:5432
    environment:
     POSTGRES_DB: control_fc
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local